In [1]:
!uv pip install .

Using Python 3.13.12 environment at: /Users/bengal1/dev/QMC-HAMM/configurations/.venv
Resolved 32 packages in 22ms
   Building qmc-db @ file:///Users/bengal1/dev/QMC-HAMM/qmc-db
   Building qmc-db @ file:///Users/bengal1/dev/QMC-HAMM/qmc-db
      Built qmc-db @ file:///Users/bengal1/dev/QMC-HAMM/qmc-db
Prepared 1 package in 309ms
Uninstalled 1 package in 0.92ms
Installed 1 package in 1ms file:///Users/bengal1/dev/QMC-HAM
 ~ qmc-db==0.1.0 (from file:///Users/bengal1/dev/QMC-HAMM/qmc-db)

In [2]:
from qmc_repo.repo import Repo

# Connect to the repository of QMC Data
repo = Repo()

In [5]:
source = repo.qmchamm_v1
source

qmchamm_v1:
  args:
    storage_options:
      anon: false
      endpoint_url: https://uri.osn.mghpcc.org
    urlpath: s3://phy240060/QMCHAMM/catalog.csv
  description: QMC HAMM Data
  driver: intake.source.csv.CSVSource
  metadata:
    catalog_dir: s3://phy240060
    origin: Example data
    version: '1.0'

In [8]:
df = source.read()
df

,uri,author,calculation_type,config_number,creation_date,method,method_kws,mixed_estimator_available,name_in_system,natoms,...,qmc_run_date,qmcpack_version,rs,species,starting_configuration_model_name,system,temperature,uuid,uuid_in_system,formula
0,s3://phy240060/QMCHAMM/10dba7b8b472ad451a382d3...,ShubhangG,qmc,81.0,2025-04-19,VMC,[b'twist_averaged' b'qmcpack_complex' b'legacy...,False,M18_LAMMPS_P140T2400config81_2025-04-19,96,...,2025_05_25,4.0-cpu-complex,1.522366,[b'H'],M18,P140T2400config81,2400.0,10dba7b8b472ad451a382d3ffc80913ac7d7b211baa79d...,M18_LAMMPS_P140T2400config81_2025-04-19,NaN
1,s3://phy240060/QMCHAMM/75e917ae2fd8099fc351b6d...,ShubhangG,qmc,81.0,2025-04-19,DMC,[b'twist_averaged' b'qmcpack_complex' b'legacy...,True,M18_LAMMPS_P140T2400config81_2025-04-19,96,...,2025_05_25,4.0-cpu-complex,1.522366,[b'H'],M18,P140T2400config81,2400.0,75e917ae2fd8099fc351b6df69c7e764bf99a98e8a97a9...,M18_LAMMPS_P140T2400config81_2025-04-19,NaN
2,s3://phy240060/QMCHAMM/CrAlN_32_atoms_CASCI.h5,['Kevin G. Kleiner' 'Lucas K. Wagner'],CASCI,NaN,2026-04-17T12:52:41.515205,CASCI,NaN,NaN,NaN,32,...,NaN,NaN,NaN,['Cr' 'Al' 'N'],NaN,CrAlN,NaN,b83b83d7-bd07-4884-924a-dcaee7a67105,NaN,CrAl15N16
3,s3://phy240060/QMCHAMM/CrAlN_32_atoms_QMC.h5,['Kevin G. Kleiner' 'Lucas K. Wagner'],QMC,NaN,2026-04-17T12:52:41.902886,VMC,NaN,NaN,NaN,32,...,NaN,NaN,NaN,['Cr' 'Al' 'N'],NaN,CrAlN,NaN,8859a39c-13b4-465c-83f5-0a5f34cd6d62,NaN,CrAl15N16
4,s3://phy240060/QMCHAMM/FeAlN_32_atoms_CASCI.h5,['Kevin G. Kleiner' 'Lucas K. Wagner'],CASCI,NaN,2026-04-17T12:52:31.819972,CASCI,NaN,NaN,NaN,32,...,NaN,NaN,NaN,['Fe' 'Al' 'N'],NaN,FeAlN,NaN,5ac120fc-4b8f-4bbb-b01b-ae931ab243af,NaN,FeAl15N16
5,s3://phy240060/QMCHAMM/FeAlN_32_atoms_QMC.h5,['Kevin G. Kleiner' 'Lucas K. Wagner'],QMC,NaN,2026-04-17T12:52:39.191844,VMC,NaN,NaN,NaN,32,...,NaN,NaN,NaN,['Fe' 'Al' 'N'],NaN,FeAlN,NaN,b7eb27cf-8ef4-4850-8cce-70213fe5420a,NaN,FeAl15N16
6,s3://phy240060/QMCHAMM/NVdiamond_31_atoms_CASC...,['Kevin G. Kleiner' 'Lucas K. Wagner'],CASCI,NaN,2026-04-17T12:52:42.833033,CASCI,NaN,NaN,NaN,31,...,NaN,NaN,NaN,['N' 'C'],NaN,NVdiamond,NaN,f737412e-c8db-406d-b78d-513f18decc66,NaN,C30N1
7,s3://phy240060/QMCHAMM/NVdiamond_31_atoms_QMC.h5,['Kevin G. Kleiner' 'Lucas K. Wagner'],QMC,NaN,2026-04-17T12:52:43.064913,VMC,NaN,NaN,NaN,31,...,NaN,NaN,NaN,['N' 'C'],NaN,NVdiamond,NaN,0731d526-16d3-45a0-ae82-4d22c27922db,NaN,C30N1
8,s3://phy240060/QMCHAMM/SiVdiamond_31_atoms_CAS...,['Kevin G. Kleiner' 'Lucas K. Wagner'],CASCI,NaN,2026-04-17T12:52:43.822533,CASCI,NaN,NaN,NaN,31,...,NaN,NaN,NaN,['Si' 'C'],NaN,SiVdiamond,NaN,8ee763eb-bfda-41d4-8d26-833d234abdc3,NaN,C30Si1
9,s3://phy240060/QMCHAMM/SiVdiamond_31_atoms_QMC.h5,['Kevin G. Kleiner' 'Lucas K. Wagner'],QMC,NaN,2026-04-17T12:52:44.301530,VMC,NaN,NaN,NaN,31,...,NaN,NaN,NaN,['Si' 'C'],NaN,SiVdiamond,NaN,0a7684e9-6972-41e6-8400-6721d324c614,NaN,C30Si1

In [12]:
diamonds = df[df["system"]=='SiVdiamond']
diamonds

,uri,author,calculation_type,config_number,creation_date,method,method_kws,mixed_estimator_available,name_in_system,natoms,...,qmc_run_date,qmcpack_version,rs,species,starting_configuration_model_name,system,temperature,uuid,uuid_in_system,formula
8,s3://phy240060/QMCHAMM/SiVdiamond_31_atoms_CAS...,['Kevin G. Kleiner' 'Lucas K. Wagner'],CASCI,NaN,2026-04-17T12:52:43.822533,CASCI,NaN,NaN,NaN,31,...,NaN,NaN,NaN,['Si' 'C'],NaN,SiVdiamond,NaN,8ee763eb-bfda-41d4-8d26-833d234abdc3,NaN,C30Si1
9,s3://phy240060/QMCHAMM/SiVdiamond_31_atoms_QMC.h5,['Kevin G. Kleiner' 'Lucas K. Wagner'],QMC,NaN,2026-04-17T12:52:44.301530,VMC,NaN,NaN,NaN,31,...,NaN,NaN,NaN,['Si' 'C'],NaN,SiVdiamond,NaN,0a7684e9-6972-41e6-8400-6721d324c614,NaN,C30Si1